version: '3'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
#    volumes:
#      - dmojData:/var/lib/postgresql/data/
    environment:
      MYSQL_DATABASE: 'dmoj'
      MYSQL_USER: 'dmoj'
      MYSQL_PASSWORD: 'root123!'
      MYSQL_ROOT_PASSWORD: 'root123!'
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always
  base:
    image: dmoj-site-base
    build:
      context: .
      dockerfile: .docker/base/Dockerfile
  static:
    image: dmoj-site-static
    build:
      context: .
      dockerfile: .docker/static/Dockerfile
    depends_on:
      - base
  site:
    build:
      context: .
      dockerfile: .docker/site/Dockerfile
    environment:
      - DEBUG=1
      - SECRET_KEY=ChangeMe
      - SQL_DATABASE_NAME=dmoj
      - SQL_DATABASE_USER=dmoj
      - 'SQL_DATABASE_PASSWORD=root123!'
      - SQL_DATABASE_HOST=db
      - SQL_DATABASE_PORT=3306
    volumes:
      - /tmp/log:/log
    ports:
      - "3031:3031"
    depends_on:
      - db
      - redis
      - base
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    volumes:
      - /tmp/log:/log
    ports:
      - "8080:80"
    depends_on:
      - static
  judge:
    restart: unless-stopped
    volumes:
      - /Users/o.hubenko/IdeaProjects/judge-server/testsuite/:/problems/
      - /Users/o.hubenko/IdeaProjects/judge-server/testsuite/judje.yml:/judge.yml
    cap_add:
      - SYS_PTRACE
    ports:
      - "9999:9999"
    image: dmoj/judge-tier1:latest
    command: run -c /judge.yml localhost
  mathoid:
    container_name: mathoid
    image: ninjaclasher/dmoj-mathoid
    restart: unless-stopped
    volumes:
      - /Users/o.hubenko/IdeaProjects/dmoj-docker/dmoj/mathoid/config.yaml:/node_modules/mathoid/config.yaml
    ports:
      - "127.0.0.1:8888:8888"
  texoid:
    container_name: texoid
    image: texoid:texoid
    build: ./texoid
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8888"