# Generated by Django 3.2.19 on 2023-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0146_theorypostgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='test title')),
                ('form', models.URLField(verbose_name='form')),
                ('authors', models.ManyToManyField(blank=True, to='judge.Profile', verbose_name='authors')),
            ],
            options={
                'verbose_name': 'test post',
                'verbose_name_plural': 'test posts',
                'permissions': (('edit_all_post', 'Edit all posts'), ('change_post_visibility', 'Edit post visibility')),
            },
        ),
    ]
