# Generated by Django 3.2.19 on 2023-06-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0148_auto_20230528_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_rated',
            field=models.BooleanField(default=False, help_text='Whether this course can be rated.', verbose_name='course rated'),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_all',
            field=models.BooleanField(default=False, help_text='Rate all users who joined.', verbose_name='rate all'),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_exclude',
            field=models.ManyToManyField(blank=True, related_name='_judge_course_rate_exclude_+', to='judge.Profile', verbose_name='exclude from ratings'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_ceiling',
            field=models.IntegerField(blank=True, help_text='Do not rate users who have a higher rating.', null=True, verbose_name='rating ceiling'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_floor',
            field=models.IntegerField(blank=True, help_text='Do not rate users who have a lower rating.', null=True, verbose_name='rating floor'),
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='rank')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('mean', models.FloatField(verbose_name='raw rating')),
                ('performance', models.FloatField(verbose_name='contest performance')),
                ('last_rated', models.DateTimeField(db_index=True, verbose_name='last rated')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='judge.course', verbose_name='course')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_rating', to='judge.courseparticipation', verbose_name='participation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'course rating',
                'verbose_name_plural': 'course ratings',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
